# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'antonym.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(542, 390)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(10, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(185, 185, 185);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(197, 197, 197);\n"
"}\n"
"\n"
"")
        self.addButton.setObjectName("addButton")
        self._ = QtWidgets.QLabel(self.centralwidget)
        self._.setGeometry(QtCore.QRect(260, 10, 20, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self._.setFont(font)
        self._.setObjectName("_")
        self.delButton = QtWidgets.QPushButton(self.centralwidget)
        self.delButton.setGeometry(QtCore.QRect(140, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.delButton.setFont(font)
        self.delButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(185, 185, 185);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(197, 197, 197);\n"
"}\n"
"\n"
"")
        self.delButton.setObjectName("delButton")
        self.verbSearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.verbSearchButton.setGeometry(QtCore.QRect(190, 100, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.verbSearchButton.setFont(font)
        self.verbSearchButton.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-left-radius: 0;\n"
"    border-bottom-right-radius:0;\n"
"    background-color: rgb(185, 185, 185);;\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(197, 197, 197);\n"
"}\n"
"\n"
"")
        self.verbSearchButton.setObjectName("verbSearchButton")
        self.saveToFile = QtWidgets.QPushButton(self.centralwidget)
        self.saveToFile.setGeometry(QtCore.QRect(280, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveToFile.setFont(font)
        self.saveToFile.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(185, 185, 185);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(197, 197, 197);\n"
"}\n"
"\n"
"")
        self.saveToFile.setObjectName("saveToFile")
        self.antonym = QtWidgets.QLabel(self.centralwidget)
        self.antonym.setGeometry(QtCore.QRect(280, 140, 251, 201))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.antonym.setFont(font)
        self.antonym.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.antonym.setStyleSheet("QLabel {\n"
"    border-radius:  10px;\n"
"    background-color:rgb(221, 221, 221);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"")
        self.antonym.setText("")
        self.antonym.setScaledContents(False)
        self.antonym.setAlignment(QtCore.Qt.AlignCenter)
        self.antonym.setWordWrap(True)
        self.antonym.setIndent(3)
        self.antonym.setObjectName("antonym")
        self.loadFromFile = QtWidgets.QPushButton(self.centralwidget)
        self.loadFromFile.setGeometry(QtCore.QRect(410, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loadFromFile.setFont(font)
        self.loadFromFile.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(185, 185, 185);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(197, 197, 197);\n"
"}\n"
"\n"
"")
        self.loadFromFile.setObjectName("loadFromFile")
        self.verbEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.verbEntry.setGeometry(QtCore.QRect(10, 10, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.verbEntry.setFont(font)
        self.verbEntry.setStyleSheet("QLineEdit {\n"
"    border-radius:  10px;\n"
"    background-color:rgb(207, 207, 207);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"")
        self.verbEntry.setText("")
        self.verbEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.verbEntry.setObjectName("verbEntry")
        self.antEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.antEntry.setGeometry(QtCore.QRect(280, 10, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.antEntry.setFont(font)
        self.antEntry.setStyleSheet("QLineEdit {\n"
"    border-radius:  10px;\n"
"    background-color:rgb(207, 207, 207);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"")
        self.antEntry.setText("")
        self.antEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.antEntry.setReadOnly(False)
        self.antEntry.setObjectName("antEntry")
        self.verbSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.verbSearch.setGeometry(QtCore.QRect(10, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.verbSearch.setFont(font)
        self.verbSearch.setStyleSheet("QLineEdit {\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    border-bottom-right-radius:0;\n"
"    background-color:rgb(206, 206, 206);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"")
        self.verbSearch.setText("")
        self.verbSearch.setAlignment(QtCore.Qt.AlignCenter)
        self.verbSearch.setObjectName("verbSearch")
        self.interLoad = QtWidgets.QPushButton(self.centralwidget)
        self.interLoad.setGeometry(QtCore.QRect(360, 350, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.interLoad.setFont(font)
        self.interLoad.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(185, 185, 185);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(197, 197, 197);\n"
"}\n"
"\n"
"")
        self.interLoad.setObjectName("interLoad")
        self.clearAll = QtWidgets.QPushButton(self.centralwidget)
        self.clearAll.setGeometry(QtCore.QRect(280, 350, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.clearAll.setFont(font)
        self.clearAll.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(185, 185, 185);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(197, 197, 197);\n"
"}\n"
"\n"
"")
        self.clearAll.setObjectName("clearAll")
        self.verbsList = QtWidgets.QListWidget(self.centralwidget)
        self.verbsList.setGeometry(QtCore.QRect(10, 130, 241, 251))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.verbsList.setFont(font)
        self.verbsList.setStyleSheet("QListWidget {\n"
"    border-style: none;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius:8px;\n"
"    background-color:rgb(221, 221, 221);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"")
        self.verbsList.setObjectName("verbsList")
        self.intSearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.intSearchButton.setGeometry(QtCore.QRect(280, 100, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.intSearchButton.setFont(font)
        self.intSearchButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(185, 185, 185);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(197, 197, 197);\n"
"}\n"
"\n"
"")
        self.intSearchButton.setObjectName("intSearchButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Словарь Антонимов"))
        self.addButton.setText(_translate("MainWindow", "Добавить"))
        self._.setText(_translate("MainWindow", ":"))
        self.delButton.setText(_translate("MainWindow", "Удалить"))
        self.verbSearchButton.setText(_translate("MainWindow", "Найти"))
        self.saveToFile.setText(_translate("MainWindow", "Сохранить"))
        self.loadFromFile.setText(_translate("MainWindow", "Загрузить"))
        self.verbEntry.setPlaceholderText(_translate("MainWindow", "Слово"))
        self.antEntry.setPlaceholderText(_translate("MainWindow", "Антоним(ы)"))
        self.verbSearch.setPlaceholderText(_translate("MainWindow", "Слово"))
        self.interLoad.setText(_translate("MainWindow", "Загрузить из интернета"))
        self.clearAll.setText(_translate("MainWindow", "Очистить"))
        self.intSearchButton.setText(_translate("MainWindow", "Найти в интернете"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
